import type { PublicSource } from "./sources";

export const ARTIST_SOURCE_CATALOG: PublicSource[] = [
  {
    id: "S30",
    title: "Bob Dylan — The Nobel Lecture (official site)",
    url: "https://www.bobdylan.com/books/the-nobel-lecture/",
    kind: "primary",
    anchors: ["bob dylan", "dylan"],
    tags: ["myth", "history", "america", "faith", "betrayal", "violence", "change", "identity", "memory", "leadership", "war"],
    note: "Use Dylan as an artist witness on American myth, moral ambiguity, history, betrayal, faith, identity, change, violence, and unstable meaning. Distinguish artistic persona and narrator from the artist; never treat one lyric or song as settled doctrine.",
  },
  {
    id: "S31",
    title: "David Byrne — How Music Works (official site)",
    url: "https://www.davidbyrne.com/explore/how-music-works/press",
    kind: "official",
    anchors: ["david byrne", "byrne"],
    tags: ["systems", "cities", "technology", "conformity", "identity", "embodiment", "absurdity", "social behavior", "design", "modernity"],
    note: "Use Byrne as an artist witness on systems, cities, technology, conformity, identity, embodiment, design, social behavior, and ordinary absurdity. Do not turn recurring artistic observations into a systematic philosophy or invent intentions.",
  },
  {
    id: "S32",
    title: "Octavia E. Butler — official author site",
    url: "https://www.octaviabutler.com/",
    kind: "official",
    anchors: ["octavia butler", "octavia e. butler"],
    tags: ["power", "hierarchy", "adaptation", "coercion", "difference", "survival", "community", "domination", "change", "leadership"],
    note: "Use Octavia E. Butler as an artist witness on power, hierarchy, adaptation, coercion, difference, survival, community, and domination. Do not reduce her fiction to dystopia or infer a single doctrine from a character, narrator, or plot outcome.",
  },
  {
    id: "S33",
    title: "Leonard Cohen — official site",
    url: "https://www.leonardcohen.com/",
    kind: "official",
    anchors: ["leonard cohen", "cohen"],
    tags: ["faith", "doubt", "love", "mortality", "failure", "repentance", "longing", "transcendence", "intimacy", "grief"],
    note: "Use Cohen as an artist witness on faith, doubt, erotic love, mortality, failure, repentance, longing, transcendence, and intimacy. Do not reduce the work to melancholy or romantic fatalism, and do not equate a song narrator with Cohen himself.",
  },
  {
    id: "S34",
    title: "Frida Kahlo — Museo Frida Kahlo / Casa Azul",
    url: "https://www.museofridakahlo.org.mx/",
    kind: "official",
    anchors: ["frida kahlo", "kahlo"],
    tags: ["embodiment", "pain", "disability", "identity", "love", "mortality", "self-representation", "suffering", "body"],
    note: "Use Kahlo as an artist witness on embodiment, pain, disability, identity, love, mortality, and self-representation. Do not collapse her work into pain alone or treat every visual symbol as autobiographical fact.",
  },
  {
    id: "S35",
    title: "Jean-Michel Basquiat — Estate of Jean-Michel Basquiat",
    url: "https://basquiat.com/",
    kind: "official",
    anchors: ["jean-michel basquiat", "basquiat"],
    tags: ["race", "commodification", "history", "colonialism", "fame", "violence", "status", "ownership", "black identity", "markets"],
    note: "Use Basquiat as an artist witness on race, commodification, history, colonial residue, fame, violence, status, cultural ownership, and Black identity. Do not reduce him to graffiti, fame, or rebellion, and do not claim a fixed symbolic dictionary for the paintings.",
  },
  {
    id: "S36",
    title: "John Lennon — official site",
    url: "https://www.johnlennon.com/",
    kind: "official",
    anchors: ["john lennon", "lennon"],
    tags: ["peace", "violence", "class", "fame", "politics", "intimacy", "masculinity", "reinvention", "utopia", "contradiction", "war"],
    note: "Use Lennon as an artist witness on peace, violence, class, fame, political awakening, intimacy, masculinity, self-reinvention, utopian imagination, and contradiction. Distinguish changing views, artistic persona, documented conduct, and collaborative work; do not reduce him to sainthood or hypocrisy.",
  },
  {
    id: "S37",
    title: "Yoko Ono — IMAGINE PEACE official archive",
    url: "https://www.imaginepeace.com/",
    kind: "official",
    anchors: ["yoko ono", "ono"],
    tags: ["conceptual art", "peace", "feminism", "participation", "grief", "war", "imagination", "vulnerability", "collaboration", "attention"],
    note: "Use Yoko Ono as an independent artist witness on conceptual art, peace, feminism, participation, grief, war, imagination, vulnerability, collaboration, social convention, and attention. Do not define her primarily through Lennon or Beatles mythology, and distinguish shared projects from her separate body of work.",
  },
];
