import type { PublicSource } from "./sources";

// Artist Witness seats added after the original eight-witness runtime registry.
// These entries provide one authoritative routing source per artist; Project
// Sources 03/04/07 retain the full medium-specific corpus architecture.
export const EXPANDED_ARTIST_SOURCE_CATALOG: PublicSource[] = [
  {
    id: "S66",
    title: "George Carlin — official archive",
    url: "https://georgecarlin.com/",
    kind: "official",
    anchors: ["george carlin", "carlin"],
    tags: ["language", "euphemism", "hypocrisy", "censorship", "class", "religion", "consumerism", "war", "nationalism", "death", "taboo"],
    note: "Use Carlin as a performance witness on language, euphemism, hypocrisy, censorship, class, religion, consumerism, war, death, and taboo. A joke premise or stage persona is not automatically literal doctrine; exact routine/version matters.",
  },
  {
    id: "S67",
    title: "Charles Bukowski Papers — The Huntington",
    url: "https://www.huntington.org/collections/lib-mssbuk-1-1693-aspace-503f79af3fa83ff98262f191ac6f7940",
    kind: "official",
    anchors: ["charles bukowski", "bukowski"],
    tags: ["class", "wage labor", "precarity", "loneliness", "addiction", "sex", "violence", "masculinity", "humiliation", "failure", "los angeles"],
    note: "Use Bukowski for class, hated work, loneliness, damaged masculinity, humiliation, failure, and outsider identity without romanticizing alcoholism, misogyny, violence, abuse, degradation, or poverty. Henry Chinaski and first-person poems are not transparent autobiography.",
  },
  {
    id: "S68",
    title: "Ursula K. Le Guin — official bibliography and works",
    url: "https://www.ursulakleguin.com/",
    kind: "official",
    anchors: ["ursula le guin", "ursula k. le guin", "le guin"],
    tags: ["power", "freedom", "anarchism", "gender", "kinship", "ecology", "language", "property", "utopia", "violence", "ambiguity", "responsibility"],
    note: "Use Le Guin as a literary witness on power, freedom, property, gender, kinship, ecology, utopia, ambiguity, and alternative social orders. Fictional societies and characters are thought experiments rather than direct doctrine; track changes across decades.",
  },
  {
    id: "S69",
    title: "Dolly Parton — official site and works",
    url: "https://dollyparton.com/",
    kind: "official",
    anchors: ["dolly parton", "parton"],
    tags: ["work", "class", "gender", "dignity", "self-fashioning", "humor", "poverty", "appalachia", "generosity", "literacy", "entrepreneurship", "authenticity"],
    note: "Use Parton on work, class, dignity, gender, humor, ambition, regional identity, generosity, literacy, entrepreneurship, and deliberate public persona. Song speakers are not autobiography, persona is not transparent private self, and philanthropy does not settle every policy question.",
  },
  {
    id: "S70",
    title: "Christopher Nolan — British Film Institute",
    url: "https://www.bfi.org.uk/people/christopher-nolan",
    kind: "official",
    anchors: ["christopher nolan", "nolan"],
    tags: ["time", "memory", "truth", "deception", "obsession", "sacrifice", "technology", "institutions", "history", "myth", "identity", "uncertainty"],
    note: "Use Nolan as a film witness on time, memory, truth, deception, obsession, technological power, institutions, myth, and audience cognition. Character is not director; director is not sole author; historical films and scientific fiction require independent verification.",
  },
  {
    id: "S71",
    title: "Steven Spielberg — Amblin",
    url: "https://amblin.com/",
    kind: "official",
    anchors: ["steven spielberg", "spielberg"],
    tags: ["wonder", "fear", "childhood", "family", "historical memory", "war", "witnessing", "antisemitism", "institutions", "technology", "popular myth", "suffering"],
    note: "Use Spielberg as a film witness where private emotion, popular myth, childhood, war, historical memory, witnessing, and institutions meet. Film character is not Spielberg, director is not sole author, and dramatized history is not historical evidence by itself.",
  },
  {
    id: "S72",
    title: "Salvador Dalí — Fundació Gala-Salvador Dalí",
    url: "https://www.salvador-dali.org/en/",
    kind: "official",
    anchors: ["salvador dali", "salvador dalí", "dali", "dalí"],
    tags: ["dream", "desire", "paranoia", "sexuality", "religion", "death", "time", "spectacle", "celebrity", "self-mythology", "irrationality", "perception"],
    note: "Use Dalí on imagination, irrationality, self-creation, spectacle, desire, mortality, and unstable perception. Authentication precedes interpretation; persona is not neutral autobiography, and recurring motifs do not form a universal symbolic dictionary.",
  },
  {
    id: "S73",
    title: "Sam Shepard — official archive and archival collections",
    url: "https://samshepardarchive.com/archives-and-collections/",
    kind: "official",
    anchors: ["sam shepard", "shepard"],
    tags: ["family", "inheritance", "masculinity", "violence", "american myth", "fathers", "sons", "rootlessness", "self-invention", "memory", "landscape", "home"],
    note: "Use Shepard on family inheritance, masculinity, violence, American myth, self-invention, memory, and unstable ideas of home. Character is not Shepard; stage text, rehearsal revision, revival, and film adaptation can differ materially; preserve collaborators.",
  },
  {
    id: "S74",
    title: "Toni Morrison — Nobel Lecture",
    url: "https://www.nobelprize.org/prizes/literature/1993/morrison/lecture/",
    kind: "primary",
    anchors: ["toni morrison", "morrison"],
    tags: ["memory", "race", "history", "inheritance", "violence", "love", "motherhood", "language", "community", "haunting", "american myth", "moral imagination"],
    note: "Use Morrison as an Artist Witness on memory, race, history, inheritance, violence, love, language, community, and moral imagination. Fictional narrators, ghosts, characters, and plots are not direct doctrine; distinguish novelist, critic, editor, lecturer, and public intellectual roles.",
  },
  {
    id: "S75",
    title: "John Steinbeck — Martha Heasley Cox Center for Steinbeck Studies",
    url: "https://www.sjsu.edu/steinbeck/",
    kind: "official",
    anchors: ["john steinbeck", "steinbeck"],
    tags: ["labor", "poverty", "migration", "dignity", "family", "violence", "loneliness", "community", "ecology", "class", "power", "american promise"],
    note: "Use Steinbeck on labor, poverty, migration, dignity, family, community, ecology, and economic power. Fiction is not social science or documentary history; preserve Ed Ricketts's collaborative and intellectual role where relevant.",
  },
  {
    id: "S76",
    title: "David Bowie — official site and archive routing",
    url: "https://www.davidbowie.com/",
    kind: "official",
    anchors: ["david bowie", "bowie"],
    tags: ["identity", "self-invention", "alienation", "fame", "performance", "authenticity", "gender presentation", "technology", "futurism", "mortality", "fragmentation", "artifice"],
    note: "Use Bowie on constructed identity, reinvention, fame, technology, mortality, alienation, and the boundary between authenticity and deliberate performance. David Jones is not reducible to any persona; song speaker is not Bowie; preserve collaborators and posthumous provenance.",
  },
  {
    id: "S77",
    title: "Jordan Peele — Monkeypaw Productions",
    url: "https://www.monkeypawproductions.com/",
    kind: "official",
    anchors: ["jordan peele", "peele"],
    tags: ["race", "horror", "satire", "spectacle", "identity", "social power", "violence", "american myth", "genre", "fear", "commodification", "representation"],
    note: "Use Peele as a film and cultural witness on race, horror, satire, spectacle, identity, representation, social power, fear, and American myth. A character or plot is not Peele's direct doctrine; distinguish writer, director, producer, performer, studio collaboration, and the interpretive claims made by critics or audiences.",
  },
  {
    id: "S78",
    title: "Mac Miller — official website and estate archive",
    url: "https://www.macmillerswebsite.com/",
    kind: "official",
    anchors: ["mac miller", "malcolm mccormick"],
    tags: ["self-invention", "artistic maturation", "ambition", "fame", "intimacy", "masculinity", "friendship", "loneliness", "altered states", "substance use", "vulnerability", "mortality", "experimentation", "success", "meaning"],
    note: "Use Mac Miller as a music and cultural witness on self-invention, artistic maturation, ambition, fame, intimacy, masculinity, friendship, loneliness, vulnerability, altered states, mortality, experimentation, and the tension between success and meaning. Song narrators are not automatically Miller; lyrics are not transparent autobiography or clinical evidence; do not read his 2018 death backward as the single key to the work.",
  },
];
