import type { PublicSource } from "./sources";

export const EXTENDED_SOURCE_CATALOG: PublicSource[] = [
  {
    id: "S19",
    title: "Stanford Encyclopedia of Philosophy — Thomas Aquinas",
    url: "https://plato.stanford.edu/entries/aquinas/",
    kind: "scholarship",
    anchors: ["aquinas", "thomas aquinas"],
    tags: ["natural law", "virtue", "reason", "conscience", "justice", "mercy", "intention", "culpability", "flourishing"],
    note: "Use Aquinas for natural law, virtue, reason, voluntary action, intention, culpability, justice, mercy, and human flourishing. Do not caricature him as faith replacing reason, and distinguish theological premises from arguments that purport to proceed by natural reason.",
  },
  {
    id: "S20",
    title: "Stanford Encyclopedia of Philosophy — Maimonides",
    url: "https://plato.stanford.edu/entries/maimonides/",
    kind: "scholarship",
    anchors: ["maimonides", "moses maimonides", "rambam"],
    tags: ["reason", "revelation", "law", "repentance", "ethics", "humility", "religion", "interpretation"],
    note: "Use Maimonides for reason and revelation, law, repentance, ethics, interpretation, and intellectual humility. Do not reduce him to religious legalism or erase the tensions between philosophical and legal-theological genres.",
  },
  {
    id: "S21",
    title: "Stanford Encyclopedia of Philosophy — Ibn Rushd (Averroes)",
    url: "https://plato.stanford.edu/entries/ibn-rushd/",
    kind: "scholarship",
    anchors: ["ibn rushd", "averroes"],
    tags: ["reason", "revelation", "law", "interpretation", "philosophy", "religion", "inquiry"],
    note: "Use Ibn Rushd for reason, revelation, law, interpretation, and philosophical inquiry. Do not frame him as simply reason against religion; his arguments address how philosophical demonstration and revealed law relate.",
  },
  {
    id: "S22",
    title: "Stanford Encyclopedia of Philosophy — W.E.B. Du Bois",
    url: "https://plato.stanford.edu/entries/dubois/",
    kind: "scholarship",
    anchors: ["du bois", "w.e.b. du bois", "web du bois"],
    tags: ["race", "democracy", "citizenship", "history", "power", "double consciousness", "reconstruction", "identity"],
    note: "Use Du Bois for race, democracy, citizenship, history, power, and double consciousness in the context of his wider body of work. Do not reduce him to a single concept or detach his political thought from historical analysis.",
  },
  {
    id: "S23",
    title: "Audre Lorde — Sister Outsider (Penguin Random House)",
    url: "https://www.penguinrandomhouse.com/books/198292/sister-outsider-by-audre-lorde/",
    kind: "official",
    anchors: ["audre lorde", "lorde"],
    tags: ["race", "gender", "sexuality", "anger", "difference", "silence", "power", "identity", "care"],
    note: "Use Lorde as an essayist and witness on race, gender, sexuality, anger, difference, silence, and power. Do not reduce her to the slogan that anger is good. This publisher page identifies Sister Outsider and its scope; narrow textual claims require caution unless the text itself is otherwise supplied.",
  },
  {
    id: "S24",
    title: "Alan Watts Organization — books and lectures",
    url: "https://alanwatts.org/",
    kind: "official",
    anchors: ["alan watts", "watts"],
    tags: ["ego", "identity", "control", "insecurity", "interconnectedness", "impermanence", "self", "anxiety", "concepts"],
    note: "Use Watts as a modern interpreter of Zen and Taoist thought on ego, identity, control, insecurity, interconnectedness, and conceptual limits. Do not treat his popular interpretations as substitutes for primary Buddhist scholarship; cross-check precise Buddhist claims against sources such as Nāgārjuna.",
  },
  {
    id: "S25",
    title: "Angela Davis — Are Prisons Obsolete? (Seven Stories Press)",
    url: "https://www.sevenstories.com/books/2907-are-prisons-obsolete",
    kind: "official",
    anchors: ["angela davis", "davis"],
    tags: ["prison", "abolition", "decarceration", "race", "gender", "structural violence", "institution", "justice", "liberation"],
    note: "Use Davis for prison abolition, decarceration, the prison-industrial complex, structural racism and gender, and alternatives to incarceration. Do not caricature abolition as merely releasing everyone; distinguish institutional critique from a specific remedy in a present case.",
  },
  {
    id: "S26",
    title: "Judith Butler — academic biography and works (EGS)",
    url: "https://pact.egs.edu/biography/judith-butler/",
    kind: "scholarship",
    anchors: ["judith butler", "butler"],
    tags: ["gender", "social norms", "vulnerability", "recognition", "precarity", "power", "identity", "accountability", "self"],
    note: "Use Butler for gender, social norms, vulnerability, recognition, precarity, power, and the limits of self-knowledge. Do not reduce performativity to the claim that gender is fake or voluntary role-play. This source is best for intellectual context and works rather than narrow textual quotation.",
  },
  {
    id: "S27",
    title: "Cornel West — Race Matters (Penguin Random House)",
    url: "https://www.penguinrandomhouse.com/books/643717/race-matters-by-cornel-west/",
    kind: "official",
    anchors: ["cornel west", "west"],
    tags: ["race", "democracy", "justice", "despair", "moral courage", "solidarity", "love", "community", "politics"],
    note: "Use West for race, democracy, justice, despair, moral courage, solidarity, and prophetic democratic critique. Do not reduce his thought to rhetoric or optimism. Keep claims tied to the works actually represented by the supplied source.",
  },
  {
    id: "S28",
    title: "Anthony Bourdain — Kitchen Confidential (HarperCollins)",
    url: "https://www.harpercollins.com/products/kitchen-confidential-anthony-bourdain",
    kind: "official",
    anchors: ["anthony bourdain", "bourdain"],
    tags: ["kitchen", "labor", "work", "restaurant", "hospitality", "class", "dignity", "exploitation", "authenticity"],
    note: "Use Bourdain as a cultural witness and moderator, never as a systematic philosopher. Kitchen Confidential can ground claims about restaurant work, kitchens, labor culture, hierarchy, craft, and lived consequence; it does not by itself establish every broader view attributed to him.",
  },
  {
    id: "S29",
    title: "Anthony Bourdain: Parts Unknown — official archive",
    url: "https://www.cnn.com/shows/anthony-bourdain-parts-unknown",
    kind: "official",
    anchors: ["anthony bourdain", "bourdain"],
    tags: ["travel", "food", "culture", "hospitality", "curiosity", "humility", "class", "dignity", "people", "place"],
    note: "Use Parts Unknown as evidence of Bourdain's recurring practice of approaching places through food, ordinary people, history, work, and lived culture. Do not convert recurring themes into a rigid doctrine or invent quotations, intentions, or views not supported by an episode or interview.",
  },
];
