import type { PublicSource } from "./sources";

// Permanent thinker/scientist/public-intellectual seats added after the original
// lightweight source registry. These are representative authoritative routes,
// not substitutes for the fuller corpus architecture maintained in Project Source 07.
export const ROSTER_SOURCE_CATALOG: PublicSource[] = [
  {
    id: "S40",
    title: "Laozi — Stanford Encyclopedia of Philosophy",
    url: "https://plato.stanford.edu/entries/laozi/",
    kind: "scholarship",
    anchors: ["laozi", "lao tzu", "daodejing", "tao te ching"],
    tags: ["dao", "wuwei", "non-coercion", "simplicity", "desire", "language", "rulership", "paradox", "reversal", "nature"],
    note: "Use Laozi for Daoist questions about non-coercive action, desire, rulership, language, reversal, and simplicity. Do not reduce wuwei to passivity or 'go with the flow'; authorship and textual history are composite and contested.",
  },
  {
    id: "S41",
    title: "V. F. Cordova — How It Is (University of Arizona Press)",
    url: "https://uapress.arizona.edu/book/how-it-is",
    kind: "official",
    anchors: ["v. f. cordova", "vf cordova", "viola cordova", "cordova"],
    tags: ["reality", "knowledge", "time", "matter", "spirit", "language", "culture", "identity", "relationality", "indigenous philosophy"],
    note: "Use Cordova for her own arguments about reality, knowledge, identity, language, culture, time, and relationality. Do not treat her as a spokesperson for every Native nation or collapse her work into a generic 'Indigenous worldview.'",
  },
  {
    id: "S42",
    title: "Vine Deloria Jr. — University of Colorado Boulder",
    url: "https://www.colorado.edu/center/west/vine-deloria-jr",
    kind: "official",
    anchors: ["vine deloria", "vine deloria jr", "deloria"],
    tags: ["sovereignty", "land", "religion", "colonialism", "law", "history", "science", "institution", "self-determination", "indigenous politics"],
    note: "Use Deloria for sovereignty, colonial institutions, land, religion, law, history, science, and Indigenous self-determination. Do not reduce his institutional and epistemic critiques to a blanket rejection of Western thought or science.",
  },
  {
    id: "S43",
    title: "Kyle Powys Whyte — University of Michigan",
    url: "https://seas.umich.edu/research/faculty/kyle-whyte",
    kind: "official",
    anchors: ["kyle whyte", "kyle powys whyte", "whyte"],
    tags: ["climate justice", "environmental ethics", "settler colonialism", "collective responsibility", "indigenous sovereignty", "future generations", "conservation", "science institutions", "kinship", "environment"],
    note: "Use Whyte for climate justice, settler colonialism, Indigenous sovereignty, conservation, science institutions, kinship, and intergenerational responsibility. Avoid romanticizing Indigenous environmental thought as simple closeness to nature.",
  },
  {
    id: "S44",
    title: "Mary Graham — University of Queensland",
    url: "https://polsis.uq.edu.au/profile/2235/mary-graham",
    kind: "official",
    anchors: ["mary graham"],
    tags: ["country", "relationality", "positionality", "custodial obligation", "governance", "responsibility", "community", "place", "aboriginal philosophy", "relationship"],
    note: "Use Graham for relationality, Country, positionality, custodial obligation, governance, responsibility, and community. Do not turn Country into scenery, property, or mystical shorthand; preserve her specific Aboriginal philosophical framework.",
  },
  {
    id: "S45",
    title: "Aileen Moreton-Robinson — Queensland University of Technology profile",
    url: "https://www.qut.edu.au/about/our-people/academic-profiles/a.moreton-robinson",
    kind: "official",
    anchors: ["aileen moreton-robinson", "moreton-robinson", "moreton robinson"],
    tags: ["indigenous sovereignty", "possession", "whiteness", "property", "race", "feminism", "law", "standpoint", "settler colonialism", "epistemology"],
    note: "Use Moreton-Robinson for sovereignty, possession, whiteness, property, race, feminism, law, and standpoint. Her former institutional profile is a routing source; current affiliation must be date-checked rather than assumed from older biography text.",
  },
  {
    id: "S46",
    title: "Tyson Yunkaporta — Deakin Indigenous Knowledge Systems Lab",
    url: "https://www.deakin.edu.au/faculty-of-arts-and-education/research/indigenous-knowledge-systems-lab",
    kind: "official",
    anchors: ["tyson yunkaporta", "yunkaporta"],
    tags: ["indigenous knowledge", "systems", "complexity", "ecology", "relationality", "cognition", "governance", "story", "custodianship", "pattern"],
    note: "Use Yunkaporta for Indigenous knowledge systems, pattern, complexity, ecology, cognition, governance, story, and custodianship. Preserve the Indigenous intellectual context and distinguish metaphor, story, method, and formal claim.",
  },
  {
    id: "S47",
    title: "Viktor E. Frankl Institute — works and archive",
    url: "https://www.viktorfrankl.org/",
    kind: "official",
    anchors: ["viktor frankl", "viktor e. frankl", "frankl"],
    tags: ["meaning", "suffering", "freedom", "responsibility", "conscience", "dignity", "hope", "mortality", "psychotherapy", "determinism"],
    note: "Use Frankl for meaning, freedom under constraint, responsibility, conscience, dignity, mortality, and existential frustration. Do not imply that suffering is intrinsically good or that victims are responsible for conditions imposed on them; separate camp testimony from clinical theory.",
  },
  {
    id: "S48",
    title: "Albert Einstein — The Collected Papers of Albert Einstein",
    url: "https://einsteinpapers.press.princeton.edu/",
    kind: "primary",
    anchors: ["albert einstein", "einstein"],
    tags: ["relativity", "science", "determinism", "realism", "pacifism", "nuclear weapons", "internationalism", "civil liberties", "scientific responsibility", "education"],
    note: "Use Einstein with source-class discipline: physics, correspondence, and public advocacy are distinct evidence. Scientific genius does not make every political, religious, or philosophical remark authoritative.",
  },
  {
    id: "S49",
    title: "Stephen Hawking Archive — Cambridge University Library",
    url: "https://archivesearch.lib.cam.ac.uk/repositories/2/resources/14315",
    kind: "official",
    anchors: ["stephen hawking", "hawking"],
    tags: ["cosmology", "black holes", "singularities", "quantum gravity", "time", "science", "disability", "technology", "uncertainty", "human future"],
    note: "Use Hawking for cosmology, black holes, singularities, time, scientific explanation, disability, and public science. Separate peer-reviewed physics from popular exposition and speculative claims about philosophy, AI, God, or humanity's future.",
  },
  {
    id: "S50",
    title: "Carl Sagan and Ann Druyan Archive — Library of Congress",
    url: "https://www.loc.gov/static/collections/rights-and-access/sagan-collection.html",
    kind: "official",
    anchors: ["carl sagan", "sagan"],
    tags: ["astronomy", "planetary science", "skepticism", "nuclear war", "environmental risk", "wonder", "humility", "science communication", "extraterrestrial life", "public responsibility"],
    note: "Use Sagan for astronomy, skepticism, science communication, nuclear risk, environmental danger, wonder, and intellectual humility. Preserve Ann Druyan's collaborative role and distinguish technical science from advocacy and speculation.",
  },
  {
    id: "S51",
    title: "J. Robert Oppenheimer Papers — Library of Congress",
    url: "https://findingaids.loc.gov/repositories/19/resources/2119",
    kind: "official",
    anchors: ["j. robert oppenheimer", "robert oppenheimer", "oppenheimer"],
    tags: ["nuclear weapons", "scientific responsibility", "state power", "secrecy", "expertise", "war", "technology", "moral responsibility", "political judgment", "security"],
    note: "Use Oppenheimer for scientific responsibility, nuclear weapons, state power, secrecy, expertise, and political judgment. Do not reduce him to one Bhagavad Gita quotation or to a single remorse narrative; distinguish wartime, postwar policy, security-hearing, scientific, and retrospective contexts.",
  },
  {
    id: "S52",
    title: "Baruch Spinoza — Stanford Encyclopedia of Philosophy",
    url: "https://plato.stanford.edu/entries/spinoza/",
    kind: "scholarship",
    anchors: ["baruch spinoza", "spinoza"],
    tags: ["freedom", "necessity", "emotion", "reason", "causation", "virtue", "democracy", "toleration", "religion", "self-mastery"],
    note: "Use Spinoza for freedom under necessity, affects, reason, causation, virtue, democracy, and toleration. Do not reduce him to fatalism, pantheism slogans, or 'everything happens for a reason.'",
  },
  {
    id: "S53",
    title: "Friedrich Nietzsche — Nietzsche Source",
    url: "https://www.nietzschesource.org/",
    kind: "primary",
    anchors: ["friedrich nietzsche", "nietzsche"],
    tags: ["morality", "genealogy", "ressentiment", "nihilism", "value creation", "truth", "suffering", "culture", "power", "self-overcoming"],
    note: "Use Nietzsche with chronology and edition control for genealogy, ressentiment, nihilism, truth, culture, suffering, and value creation. Do not reduce him to 'might makes right' or treat The Will to Power as a Nietzsche-authored finished book.",
  },
  {
    id: "S54",
    title: "John Rawls — Stanford Encyclopedia of Philosophy",
    url: "https://plato.stanford.edu/entries/rawls/",
    kind: "scholarship",
    anchors: ["john rawls", "rawls"],
    tags: ["justice", "fairness", "basic liberties", "equality", "distribution", "legitimacy", "public reason", "civil disobedience", "institutions", "opportunity"],
    note: "Use Rawls for justice as fairness, basic liberties, fair equality of opportunity, distributive justice, legitimacy, public reason, and civil disobedience. The original position is a justificatory device, not a historical event.",
  },
  {
    id: "S55",
    title: "Karl Marx — Stanford Encyclopedia of Philosophy",
    url: "https://plato.stanford.edu/entries/marx/",
    kind: "scholarship",
    anchors: ["karl marx", "marx"],
    tags: ["capital", "labor", "exploitation", "alienation", "class", "commodity", "ideology", "political economy", "emancipation", "history"],
    note: "Use Marx for labor, capital, exploitation, alienation, class, ideology, political economy, and emancipation. Preserve chronology, Engels's editorial/coauthorial role, and the difference between Marx and later Marxist traditions.",
  },
  {
    id: "S56",
    title: "Adam Smith — Stanford Encyclopedia of Philosophy",
    url: "https://plato.stanford.edu/entries/smith-moral-political/",
    kind: "scholarship",
    anchors: ["adam smith"],
    tags: ["sympathy", "moral judgment", "self-command", "justice", "markets", "commercial society", "division of labor", "inequality", "institutions", "character"],
    note: "Use Smith for sympathy, moral judgment, self-command, justice, commercial society, division of labor, inequality, and institutions. Do not caricature him as 'greed is good' or laissez-faire absolutism.",
  },
  {
    id: "S57",
    title: "Sigmund Freud — Freud Museum London",
    url: "https://www.freud.org.uk/learn/discover-sigmund-freud/",
    kind: "official",
    anchors: ["sigmund freud", "freud"],
    tags: ["unconscious", "repression", "conflict", "sexuality", "aggression", "guilt", "dreams", "repetition", "mourning", "civilization"],
    note: "Use Freud historically for psychoanalytic concepts such as repression, conflict, mourning, dreams, repetition, and civilization. Historical psychoanalytic theory is not current empirical psychology by default; distinguish clinical observation, metapsychology, and cultural interpretation.",
  },
  {
    id: "S58",
    title: "Charles Darwin — Darwin Online",
    url: "https://darwin-online.org.uk/",
    kind: "primary",
    anchors: ["charles darwin", "darwin"],
    tags: ["evolution", "natural selection", "common descent", "variation", "adaptation", "sexual selection", "human continuity", "science", "animals", "inference"],
    note: "Use Darwin for evolution, natural selection, common descent, adaptation, sexual selection, and scientific inference. Evolution does not entail social Darwinism, moral hierarchy, or a political program; separate Darwin's science from later ideological uses.",
  },
  {
    id: "S59",
    title: "William James — Stanford Encyclopedia of Philosophy",
    url: "https://plato.stanford.edu/entries/james/",
    kind: "scholarship",
    anchors: ["william james"],
    tags: ["pragmatism", "pluralism", "experience", "consciousness", "habit", "attention", "emotion", "will", "belief", "religious experience"],
    note: "Use James for pragmatism, pluralism, experience, habit, attention, emotion, belief, and religious experience. Pragmatism does not mean that whatever is useful is simply true, and the will to believe is not a license for arbitrary belief.",
  },
  {
    id: "S60",
    title: "George Orwell — The Orwell Foundation",
    url: "https://www.orwellfoundation.com/the-orwell-foundation/orwell/",
    kind: "official",
    anchors: ["george orwell", "orwell"],
    tags: ["political language", "propaganda", "authoritarianism", "class", "poverty", "empire", "truth", "intellectual honesty", "democratic socialism", "power"],
    note: "Use Orwell for political language, propaganda, authoritarianism, class, poverty, empire, truth, and intellectual honesty. Do not reduce him to generic anti-communism or a free-speech mascot; fiction is not automatic doctrine.",
  },
  {
    id: "S61",
    title: "Toni Morrison — Nobel Lecture",
    url: "https://www.nobelprize.org/prizes/literature/1993/morrison/lecture/",
    kind: "primary",
    anchors: ["toni morrison", "morrison"],
    tags: ["language", "memory", "race", "history", "inheritance", "violence", "love", "community", "literature", "moral imagination"],
    note: "Use Morrison as novelist, critic, editor, lecturer, and public intellectual on language, memory, race, history, inheritance, violence, and moral imagination. Fictional characters, narrators, ghosts, and plots are not direct statements of doctrine.",
  },
  {
    id: "S62",
    title: "Martin Luther King Jr. — Stanford King Institute",
    url: "https://kinginstitute.stanford.edu/",
    kind: "official",
    anchors: ["martin luther king", "martin luther king jr", "mlk", "king jr"],
    tags: ["nonviolence", "justice", "civil disobedience", "love", "dignity", "democracy", "segregation", "war", "poverty", "labor"],
    note: "Use King through the full corpus of sermons, speeches, letters, books, and papers on nonviolence, justice, dignity, democracy, war, poverty, and labor. Do not reduce him to 'I Have a Dream' or passive nonviolence; chronology matters.",
  },
  {
    id: "S63",
    title: "Carl G. Jung — Philemon Foundation",
    url: "https://philemonfoundation.org/",
    kind: "official",
    anchors: ["carl jung", "carl g. jung", "jung"],
    tags: ["analytical psychology", "complexes", "archetypes", "individuation", "shadow", "symbol", "dream", "myth", "religion", "projection"],
    note: "Use Jung historically for analytical psychology, complexes, individuation, projection, symbol, dream, and myth. Archetypes are not scientifically established universal entities by default; distinguish Jung's writings from later Jungian developments.",
  },
  {
    id: "S64",
    title: "Richard Feynman — The Feynman Lectures on Physics (Caltech)",
    url: "https://www.feynmanlectures.caltech.edu/",
    kind: "primary",
    anchors: ["richard feynman", "feynman"],
    tags: ["physics", "quantum mechanics", "uncertainty", "scientific explanation", "problem solving", "pedagogy", "intellectual honesty", "evidence", "public responsibility", "science"],
    note: "Use Feynman for physics, scientific explanation, uncertainty, pedagogy, problem solving, and intellectual honesty. His charisma and anecdotes are not substitutes for scientific work, and views outside physics are not automatically authoritative.",
  },
  {
    id: "S65",
    title: "Jane Goodall Institute Gombe Archive — Arizona State University",
    url: "https://iho.asu.edu/primate-behavior/JGI",
    kind: "official",
    anchors: ["jane goodall", "goodall"],
    tags: ["chimpanzees", "animal behavior", "tool use", "social learning", "conservation", "human animal continuity", "stewardship", "field observation", "science", "ecology"],
    note: "Use Goodall for long-term chimpanzee observation, animal individuality, tool use, social learning, conservation, and human-animal continuity. Separate observation, interpretation, advocacy, and later conservation ethics; avoid romanticizing chimpanzees or fieldwork.",
  },
];
